/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import javax.swing.JOptionPane;

/**
 *
 * @author Ignacio
 */
public class EditImpresion extends javax.swing.JFrame {

    /**
     * Creates new form EditImpresion
     */
    
    public EditImpresion() {
        initComponents();
        this.setDefaultCloseOperation(1);
        BinaryHeap helper = new BinaryHeap();
        helper = helper.clone(InterfazInicial.impresionList.getRoot(), helper);
        for (int i = 0; i < InterfazInicial.hashTable.tableSize; i++) {
            if (InterfazInicial.hashTable.tabla[i] != null) {
                usuarioBox.addItem(InterfazInicial.hashTable.tabla[i].getInformacionUsuario().getName());
                System.out.println("Entro");

            }
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eraseSelection = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        usuarioBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        seleccionarButton = new javax.swing.JButton();
        documentosBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eraseSelection.setText("Eliminar");
        eraseSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eraseSelectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eraseSelectionMouseEntered(evt);
            }
        });
        getContentPane().add(eraseSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 100, -1));

        exit.setText("Regresar");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        getContentPane().add(usuarioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 195, -1));

        jLabel2.setText("Usuarios con documentos en cola de impresión:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        seleccionarButton.setText("Seleccionar");
        seleccionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarButtonMouseClicked(evt);
            }
        });
        getContentPane().add(seleccionarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(documentosBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        jLabel3.setText("Documento a eliminar de la cola de impresión:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void eraseSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eraseSelectionMouseClicked

        HashNode eliminar = InterfazInicial.hashTable.buscar(usuarioBox.getSelectedItem().toString().toLowerCase(), documentosBox.getSelectedItem().toString());
        InterfazInicial.impresionList.searchNode(InterfazInicial.impresionList.getRoot(), eliminar.getInformacionDocumento().getTitle()).setTime(0);
        InterfazInicial.impresionList.order2(InterfazInicial.impresionList.searchNode(InterfazInicial.impresionList.getRoot(), eliminar.getInformacionDocumento().getTitle()));
        InterfazInicial.impresionList.eraseMin2().setWaiting2();
        InterfazInicial.hashTable.Eliminar(usuarioBox.getSelectedItem().toString().toLowerCase(), documentosBox.getSelectedItem().toString());
        //Eliminar de la Tabla de Dispersión
        //InterfazInicial.impresionList.eraseMin2().setWaiting2(); //Agregué esto
        JOptionPane.showMessageDialog(null, "Archivo eliminado exitosamente de la lista de impresion");
        this.dispose();
    }//GEN-LAST:event_eraseSelectionMouseClicked

    private void eraseSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eraseSelectionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eraseSelectionMouseEntered

    private void seleccionarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarButtonMouseClicked
        // TODO add your handling code here:
        documentosBox.removeAllItems();
        String usuario = usuarioBox.getSelectedItem().toString();
        for (int i = 0; i < InterfazInicial.hashTable.tableSize; i++) {
            if (InterfazInicial.hashTable.tabla[i] != null) {
                if (InterfazInicial.hashTable.tabla[i].getInformacionUsuario().getName().equalsIgnoreCase(usuario)) {
                    documentosBox.addItem(InterfazInicial.hashTable.tabla[i].getInformacionDocumento().getTitle());
                    if (InterfazInicial.hashTable.tabla[i].getNext() != null) {
                        HashNode aux = InterfazInicial.hashTable.tabla[i].getNext();
                        while (aux != null){
                            documentosBox.addItem(aux.getInformacionDocumento().getTitle());
                            aux = aux.getNext();
                        }
                    }
                }   
            }
        }
    }//GEN-LAST:event_seleccionarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditImpresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> documentosBox;
    private javax.swing.JButton eraseSelection;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton seleccionarButton;
    private javax.swing.JComboBox<String> usuarioBox;
    // End of variables declaration//GEN-END:variables
}
